src/Entity/Occasions.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OccasionsRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Occasions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modele;

    /**
     * @ORM\Column(type="integer")
     */
    private $km;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $cylindree;

    /**
     * @ORM\Column(type="integer")
     */
    private $puissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $carburant;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_circu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $transmission;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $options;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_proprio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imgCouv;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Gallery", mappedBy="occasion", orphanRemoval=true)
     */
    private $gallery;

    public function __construct()
    {
        $this->gallery = new ArrayCollection();
    }


    /**
     * Permet d'intialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->annee_circu.'-'.$this->modele);
        }

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCylindree(): ?int
    {
        return $this->cylindree;
    }

    public function setCylindree(int $cylindree): self
    {
        $this->cylindree = $cylindree;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(int $puissance): self
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): self
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getAnneeCircu(): ?int
    {
        return $this->annee_circu;
    }

    public function setAnneeCircu(int $annee_circu): self
    {
        $this->annee_circu = $annee_circu;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): self
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getOptions(): ?string
    {
        return $this->options;
    }

    public function setOptions(string $options): self
    {
        $this->options = $options;

        return $this;
    }

    public function getNombreProprio(): ?int
    {
        return $this->nombre_proprio;
    }

    public function setNombreProprio(int $nombre_proprio): self
    {
        $this->nombre_proprio = $nombre_proprio;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImgCouv(): ?string
    {
        return $this->imgCouv;
    }

    public function setImgCouv(string $imgCouv): self
    {
        $this->imgCouv = $imgCouv;

        return $this;
    }

    /**
     * @return Collection|Gallery[]
     */
    public function getGallery(): Collection
    {
        return $this->gallery;
    }

    public function addGallery(Gallery $gallery): self
    {
        if (!$this->gallery->contains($gallery)) {
            $this->gallery[] = $gallery;
            $gallery->setOccasion($this);
        }

        return $this;
    }

    public function removeGallery(Gallery $gallery): self
    {
        if ($this->gallery->contains($gallery)) {
            $this->gallery->removeElement($gallery);
            // set the owning side to null (unless already changed)
            if ($gallery->getOccasion() === $this) {
                $gallery->setOccasion(null);
            }
        }

        return $this;
    }
}

src/Controller/OccasController.php
<?php

namespace App\Controller;

use App\Entity\Occasions;
use App\Entity\Gallery;
use App\Form\AnnonceType;
use App\Controller\OccasController;
use App\Repository\GalleryRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OccasController extends AbstractController
{
    /**
     * @Route("/occas", name="occas_view")
     */
    public function index()  
    {
        $repo = $this->getDoctrine()->getRepository(Occasions::class);

        $occasions = $repo->findAll();
        return $this->render('occas/index.html.twig', [
            'controller_name' => 'OccasController',
            'occasions' => $occasions
        ]);
    }
    
      /**
     * Permet de créer une annonce
     * @Route("/occas/new", name="occas_create")
     *
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager){
        $occasion = new Occasions();
        /*
        $image1 = new Image();

        $image1->setUrl('http://placehold.it/400x200')
            ->setCaption('Titre 1');
            $occasion->addImage($image1);
        */
        $form = $this->createForm(AnnonceType::class, $occasion);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            foreach($occasion->getGallery() as $gallery){
            $gallery->setOccasion($occasion);
            $manager->persist($gallery);
            }

            $manager->persist($occasion);
            $manager->flush(); 
            

            $this->addFlash(
                'success',
                "L'annonce <strong>{$occasion->getModele()}</strong> a bien été enregistrée ! "
            );

            return $this->redirectToRoute('occas_view',[
                'slug' => $occasion->getSlug()
            ]);
        }

        return $this->render('occas/new.html.twig', [
           'myForm' => $form->createView()
        ]);

    } 


      /**
     * @Route("/occas/{slug}", name="occas_show")
     *
     * @return Response
     */
    public function show($slug, Occasions $occasions){

        //$occas = $repo->findOneBySlug($slug);

        return $this->render('occas/show.html.twig',[
          'occasions' => $occasions
        ]);

    }

 


  
}

templates/occas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Occasions{% endblock %}
{% set url = path("occas_create") %}
{% block body %}

<div class= "occastitle">Nos occasions</div>
<div class="slideoccas">

{% for occasion in occasions %}
        {% set url = path('occas_show', {'slug': occasion.slug }) %}
<a href="{{ url }}"><div class="cardbox">
<div class="modele">{{occasion.marque}} - {{occasion.modele}}</div>
<div class="couv"><img src="{{occasion.imgCouv}}" alt="image"></div>
<div class="km">{{occasion.km}} km</div>
<div class="prix">{{occasion.prix}} €</div>


</div></a>
{% endfor %}

</div>
{% endblock %}

templates/occas/new.html.twig
{% extends 'base.html.twig' %}
    {% block title %}Annoncer{% endblock %}

{% form_theme myForm _self %}

    {% block body %}
    <div class="slidenew">
    {% set url = path("occas_view") %}
         <h1 class="textnew">Créer une nouvelle annonce</h1>
    <div class="container" style="height:100%;">
    <div class="row">
       <div class="col-md-12">
    {{ form_start(myForm) }}

    {{ form_widget(myForm) }}

    <button type="submit" class="btn" style="color:white;font-size:50px">Créer mon annonce</button>
    {{ form_end(myForm) }}

       </div>
    
    </div>
   

</div>
    </div>
    {% endblock %}
{% block _annonce_gallery_widget %}

    <p>ici, vous pouvez ajouter vos propres images</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn ">Ajouter une image</button>
    </div>
  {% endblock %}
{% block _annonce_gallery_entry_row %}
    {# entry précise le entry_type de notre AnnonceType au niveau de la collection - donc chaque formulaire ImageType #}
    {# permet de juste afficher le widget donc plus les 0 1 2 3 ...#}
    {{ form_widget(form) }}

{% endblock %}


{% block _annonce_gallery_entry_widget %}
    {# entry précise le entry_type de notre AnnonceType au niveau de la collection - donc chaque formulaire ImageType #}
    <div class="form-group" id="block_{{id}}"> {# id est une variable du block - block_annonce_images_0 #}
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class=" btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
{% endblock %}




  {% block javascripts %} 
  <script>
      $('#add-image').click(function(){
            //compter combien j'ai de form-group pour les indices ex: annonce_images_0_url
            const index = +$("#widgets-counter").val(); // le + permet de transformer en nombre pcq val() rend tjrs un type string

            // récup le prototype des entrées data-prototype
            const tmpl = $('#annonce_gallery').data('prototype').replace(/__name__/g, index); // drapeau g pour indiquer qu'on va le faire plusieurs fois

            // injecter le code dans la div
            $('#annonce_gallery').append(tmpl);

            $('#widgets-counter').val(index+1);

            // gére le bouton supprimer 

            handleDeleteButtons();

        });    

        function updateCounter(){
            const count = +$('#annonce_gallery div.form-group').length;

            $('#widgets-counter').val(count);
        }


        function handleDeleteButtons(){
            $('button[data-action="delete"]').click(function(){
                const target = this.dataset.target; // dataset (les attributs data et je veux le target)
                $(target).remove();
            });
        }

        updateCounter();
        handleDeleteButtons();
    
  
  


  </script>
  {% endblock %}

templates/occas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du produit{% endblock %}

{% block body %}
<div class="slideshow">
    <div class="container opacity">
        <div class="annonce-title" style=" width:100%; height:100%;">
            <img src="{{occasions.imgCouv}}">
           <span class="spanshow"> <h1>{{ occasions.marque }} - {{occasions.modele}}</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus dolore molestias commodi tempora eligendi nostrum incidunt labore, vel, consequatur consequuntur consectetur ut expedita eius sequi illum, fugiat nisi quasi harum dolores sunt. Ipsum, labore ullam cumque eaque amet perspiciatis quasi.</p>
            <p class="h2"><strong>{{ occasions.km }} km</strong> pour un prix de <strong>{{ occasions.prix }}</strong>€</p>
        </div>
    </div>

    <div class="container">
            <div>
                <h1>Nombre de propriétaires :</h1> <h6>{{ occasions.NombreProprio }}</h6>
                <h1>Cylindrée :</h1> <h6>{{ occasions.cylindree }}L</h6>
                <h1>Puissance :</h1> <h6>{{ occasions.puissance }}ch</h6>
                <h1>Carburant :</h1> <h6>{{ occasions.carburant }}</h6>
                <h1>Année de mise en circulation :</h1> <h6>{{ occasions.anneeCircu }}</h6>
                <h1>Transmission :</h1> <h6>{{ occasions.transmission }}</h6>
                <h1>Options : </h1><p>{{ occasions.options }}</p>
                <h1>Description :</h1>{{ occasions.description | raw}}
                </div>
                {#
                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for gallery in occasions.gallery %}
                            <li data-target="#carouselExampleCaptions" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner">

                            {% for gallery in occasions.gallery %}
                            
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img src="http://placehold.it/500x500" class="d-block w-100"  alt="image de {{ occasions.modele }}">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{  occasions.modele  }}</h5>
                                    <p>{{ gallery.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        
                        </div>
                            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                    </div>
                </div>
                #}
                <div style="clear:both;">&nbsp;</div>
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for gallery in occasions.gallery %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                     {% for gallery in occasions.gallery %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img class="d-block w-100" src="https://www.placecage.com/640/360" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{  occasions.modele  }}</h5>
                                <p>{{ gallery.caption }}</p>
                            </div>
                        </div>
                    {% endfor %}    
                        
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
    {% block javascripts %}{% endblock %}